// AUTO-GENERATED by scripts/generate-sources.mjs. Do not edit by hand.
// Re-run: bun run --cwd apps/web sources
// biome-ignore-all lint/suspicious/noArrayIndexKey: source code stored as strings; lints don't apply
// biome-ignore-all lint/suspicious/noTemplateCurlyInString: source code stored as strings; lints don't apply

export const previewLoaders: Record<
  string,
  () => Promise<Record<string, unknown>>
> = {
  "AreaChart/AreaChart": () =>
    import("@workspace/compositions/compositions/AreaChart/AreaChart"),
  "BarChart/BarChart": () =>
    import("@workspace/compositions/compositions/BarChart/BarChart"),
  "BounceCards/BounceCards": () =>
    import("@workspace/compositions/compositions/BounceCards/BounceCards"),
  "BrowserWindow/BrowserWindow": () =>
    import("@workspace/compositions/compositions/BrowserWindow/BrowserWindow"),
  "CaptionTrack/CaptionTrack": () =>
    import("@workspace/compositions/compositions/CaptionTrack/CaptionTrack"),
  "CaptionedVideo/CaptionedVideo": () =>
    import("@workspace/compositions/compositions/CaptionedVideo/CaptionedVideo"),
  "CursorWalkthrough/CursorWalkthrough": () =>
    import("@workspace/compositions/compositions/CursorWalkthrough/CursorWalkthrough"),
  "DiscordMessages/DiscordMessages": () =>
    import("@workspace/compositions/compositions/DiscordMessages/DiscordMessages"),
  "GaiaScenario/GaiaScenario": () =>
    import("@workspace/compositions/compositions/GaiaScenario/GaiaScenario"),
  "GitHubStarButton/GitHubStarButton": () =>
    import("@workspace/compositions/compositions/GitHubStarButton/GitHubStarButton"),
  "ImageScene/ImageScene": () =>
    import("@workspace/compositions/compositions/ImageScene/ImageScene"),
  "InstagramMessages/InstagramMessages": () =>
    import("@workspace/compositions/compositions/InstagramMessages/InstagramMessages"),
  "InstagramPost/InstagramPost": () =>
    import("@workspace/compositions/compositions/InstagramPost/InstagramPost"),
  "LaptopFrame/LaptopFrame": () =>
    import("@workspace/compositions/compositions/LaptopFrame/LaptopFrame"),
  "LineChart/LineChart": () =>
    import("@workspace/compositions/compositions/LineChart/LineChart"),
  "LockScreenMessage/LockScreenMessage": () =>
    import("@workspace/compositions/compositions/LockScreenMessage/LockScreenMessage"),
  "LogoCloud/LogoCloud": () =>
    import("@workspace/compositions/compositions/LogoCloud/LogoCloud"),
  "MessageBubbles/MessageBubbles": () =>
    import("@workspace/compositions/compositions/MessageBubbles/MessageBubbles"),
  "PhoneFrame/PhoneFrame": () =>
    import("@workspace/compositions/compositions/PhoneFrame/PhoneFrame"),
  "PieChart/PieChart": () =>
    import("@workspace/compositions/compositions/PieChart/PieChart"),
  "PricingCard/PricingCard": () =>
    import("@workspace/compositions/compositions/PricingCard/PricingCard"),
  "Project/Project": () =>
    import("@workspace/compositions/compositions/Project/Project"),
  "QrCode/QrCode": () =>
    import("@workspace/compositions/compositions/QrCode/QrCode"),
  "RadarChart/RadarChart": () =>
    import("@workspace/compositions/compositions/RadarChart/RadarChart"),
  "RadialChart/RadialChart": () =>
    import("@workspace/compositions/compositions/RadialChart/RadialChart"),
  "Showcase/Showcase": () =>
    import("@workspace/compositions/compositions/Showcase/Showcase"),
  "SlackMessages/SlackMessages": () =>
    import("@workspace/compositions/compositions/SlackMessages/SlackMessages"),
  "SplitStack/SplitStack": () =>
    import("@workspace/compositions/compositions/SplitStack/SplitStack"),
  "SpotifyPlayer/SpotifyPlayer": () =>
    import("@workspace/compositions/compositions/SpotifyPlayer/SpotifyPlayer"),
  "StatCounter/StatCounter": () =>
    import("@workspace/compositions/compositions/StatCounter/StatCounter"),
  "TelegramMessages/TelegramMessages": () =>
    import("@workspace/compositions/compositions/TelegramMessages/TelegramMessages"),
  "Terminal/Terminal": () =>
    import("@workspace/compositions/compositions/Terminal/Terminal"),
  "TestimonialCard/TestimonialCard": () =>
    import("@workspace/compositions/compositions/TestimonialCard/TestimonialCard"),
  "Text/Text": () =>
    import("@workspace/compositions/compositions/Text/Text"),
  "TextBlurOutUp/TextBlurOutUp": () =>
    import("@workspace/compositions/compositions/TextBlurOutUp/TextBlurOutUp"),
  "TextBottomUpLetters/TextBottomUpLetters": () =>
    import("@workspace/compositions/compositions/TextBottomUpLetters/TextBottomUpLetters"),
  "TextDepthParallaxWords/TextDepthParallaxWords": () =>
    import("@workspace/compositions/compositions/TextDepthParallaxWords/TextDepthParallaxWords"),
  "TextFadeThrough/TextFadeThrough": () =>
    import("@workspace/compositions/compositions/TextFadeThrough/TextFadeThrough"),
  "TextFocusBlurResolve/TextFocusBlurResolve": () =>
    import("@workspace/compositions/compositions/TextFocusBlurResolve/TextFocusBlurResolve"),
  "TextKineticCenterBuild/TextKineticCenterBuild": () =>
    import("@workspace/compositions/compositions/TextKineticCenterBuild/TextKineticCenterBuild"),
  "TextLineByLineSlide/TextLineByLineSlide": () =>
    import("@workspace/compositions/compositions/TextLineByLineSlide/TextLineByLineSlide"),
  "TextMagicMove/TextMagicMove": () =>
    import("@workspace/compositions/compositions/TextMagicMove/TextMagicMove"),
  "TextMaskRevealUp/TextMaskRevealUp": () =>
    import("@workspace/compositions/compositions/TextMaskRevealUp/TextMaskRevealUp"),
  "TextMicroScaleFade/TextMicroScaleFade": () =>
    import("@workspace/compositions/compositions/TextMicroScaleFade/TextMicroScaleFade"),
  "TextMorph/TextMorph": () =>
    import("@workspace/compositions/compositions/TextMorph/TextMorph"),
  "TextPerCharacterRise/TextPerCharacterRise": () =>
    import("@workspace/compositions/compositions/TextPerCharacterRise/TextPerCharacterRise"),
  "TextPerWordCrossfade/TextPerWordCrossfade": () =>
    import("@workspace/compositions/compositions/TextPerWordCrossfade/TextPerWordCrossfade"),
  "TextScaleDownFade/TextScaleDownFade": () =>
    import("@workspace/compositions/compositions/TextScaleDownFade/TextScaleDownFade"),
  "TextSharedAxisX/TextSharedAxisX": () =>
    import("@workspace/compositions/compositions/TextSharedAxisX/TextSharedAxisX"),
  "TextSharedAxisY/TextSharedAxisY": () =>
    import("@workspace/compositions/compositions/TextSharedAxisY/TextSharedAxisY"),
  "TextSharedAxisZ/TextSharedAxisZ": () =>
    import("@workspace/compositions/compositions/TextSharedAxisZ/TextSharedAxisZ"),
  "TextShimmerSweep/TextShimmerSweep": () =>
    import("@workspace/compositions/compositions/TextShimmerSweep/TextShimmerSweep"),
  "TextShortSlideDown/TextShortSlideDown": () =>
    import("@workspace/compositions/compositions/TextShortSlideDown/TextShortSlideDown"),
  "TextShortSlideRight/TextShortSlideRight": () =>
    import("@workspace/compositions/compositions/TextShortSlideRight/TextShortSlideRight"),
  "TextSoftBlurIn/TextSoftBlurIn": () =>
    import("@workspace/compositions/compositions/TextSoftBlurIn/TextSoftBlurIn"),
  "TextSpringScaleIn/TextSpringScaleIn": () =>
    import("@workspace/compositions/compositions/TextSpringScaleIn/TextSpringScaleIn"),
  "TextStaggerFromCenter/TextStaggerFromCenter": () =>
    import("@workspace/compositions/compositions/TextStaggerFromCenter/TextStaggerFromCenter"),
  "TextStaggerFromEdges/TextStaggerFromEdges": () =>
    import("@workspace/compositions/compositions/TextStaggerFromEdges/TextStaggerFromEdges"),
  "TextTopDownLetters/TextTopDownLetters": () =>
    import("@workspace/compositions/compositions/TextTopDownLetters/TextTopDownLetters"),
  "TextTypewriter/TextTypewriter": () =>
    import("@workspace/compositions/compositions/TextTypewriter/TextTypewriter"),
  "TikTokCaption/TikTokCaption": () =>
    import("@workspace/compositions/compositions/TikTokCaption/TikTokCaption"),
  "TitleFade/TitleFade": () =>
    import("@workspace/compositions/compositions/TitleFade/TitleFade"),
  "TitlePopup/TitlePopup": () =>
    import("@workspace/compositions/compositions/TitlePopup/TitlePopup"),
  "TitleSlideUp/TitleSlideUp": () =>
    import("@workspace/compositions/compositions/TitleSlideUp/TitleSlideUp"),
  "TitleType/TitleType": () =>
    import("@workspace/compositions/compositions/TitleType/TitleType"),
  "TweetCard/TweetCard": () =>
    import("@workspace/compositions/compositions/TweetCard/TweetCard"),
  "TweetPost/TweetPost": () =>
    import("@workspace/compositions/compositions/TweetPost/TweetPost"),
  "TypingComposer/TypingComposer": () =>
    import("@workspace/compositions/compositions/TypingComposer/TypingComposer"),
  "TypingSearch/TypingSearch": () =>
    import("@workspace/compositions/compositions/TypingSearch/TypingSearch"),
  "WhatsAppMessages/WhatsAppMessages": () =>
    import("@workspace/compositions/compositions/WhatsAppMessages/WhatsAppMessages"),
  "backgrounds/AuroraGradient/AuroraGradient": () =>
    import("@workspace/compositions/compositions/backgrounds/AuroraGradient/AuroraGradient"),
  "backgrounds/BlueGrid/BlueGrid": () =>
    import("@workspace/compositions/compositions/backgrounds/BlueGrid/BlueGrid"),
  "backgrounds/FuturisticArch/FuturisticArch": () =>
    import("@workspace/compositions/compositions/backgrounds/FuturisticArch/FuturisticArch"),
  "backgrounds/LiquidChrome/LiquidChrome": () =>
    import("@workspace/compositions/compositions/backgrounds/LiquidChrome/LiquidChrome"),
  "backgrounds/WhiteRadialBurst/WhiteRadialBurst": () =>
    import("@workspace/compositions/compositions/backgrounds/WhiteRadialBurst/WhiteRadialBurst"),
};
